### ISSUE TITLE
Update for registry.terraform.io split

### ISSUE THREAD

**Issue by acdha** [apparentlymart/terraform-credentials-env#1]
I had a previously working configuration which broke as soon as I started the process of upgrading to Terraform 0.13. It looks like the requests to registry.terraform.io are being caught in this even though I was under the impression that registry.terraform.io did not require authentication:

```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider -/aws: failed
to retrieve credentials for registry.terraform.io: error in
/terraformer/.terraform.d/plugins/terraform-credentials-env_v1.0.0_x4: No
credentials for registry.terraform.io are defined via environment variables.
```

**Comment by bendrucker** [comment]
See https://github.com/hashicorp/terraform/issues/25938
